[project]
name = "fp"
version = "0.1.0"
description = "Functional Programming in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "polars>=1.31.0",
]
